# Generated by Django 3.2.12 on 2023-07-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('eng_name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='detail_images')),
                ('description', models.CharField(max_length=250)),
                ('year', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('slogan', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=128)),
                ('rating', models.CharField(max_length=128)),
                ('num_rating', models.CharField(max_length=128)),
                ('reviews', models.CharField(max_length=128)),
            ],
        ),
    ]
