# Generated by Django 3.2.12 on 2023-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfilm',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
