# Generated by Django 3.2.12 on 2023-07-12 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_reviews', models.TextField(max_length=2000)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filmdescription')),
                ('rating_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
